services:
  - type: web
    name: smartattend-api
    env: docker
    region: ohio
    plan: starter
    envVars:
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
